manifestVersion: subsquid.io/v0.1
name: gs-explorer-moonbase
version: 1
description: |-
  Giant Squid Explorer for Moonbase chain
build:

deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN:
        moonbase
    cmd: [ "node", "lib/processor" ]
  api:
    cmd: [ "npx", "squid-graphql-server", "--dumb-cache", "in-memory", "--dumb-cache-ttl", "1000", "--dumb-cache-size", "100", "--dumb-cache-max-age", "1000" ]

scale:
  processor:
    profile: large
  addons:
     postgres:
         storage: 400G
         profile: large